package com.bhumika.entity;

import java.time.LocalDate;
import java.util.Date;

import org.antlr.v4.runtime.misc.NotNull;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Entity
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "product_table")
public class Product {
    /**
     * The unique identifier for each product.
     * It is auto-generated by the database and annotated with JPA annotations.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "productId")
    private Integer productId;

    /**
     * The name of the product.
     * It is a string and annotated with JPA annotations to map it to the
     * "productName" column in the database.
     */
    @Column(name = "productName")
    private String productName;

    /**
     * The date when the product was created.
     * It is a LocalDate object and annotated with JPA annotations to map it to the
     * "createdOn" column in the database.
     */
    @Column(name = "createdOn")
    private LocalDate createdOn;
}